// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo41SzxHWrvvEMtyWmx3rn95SjujZkwi0',
    appId: '1:368339982928:web:bc6fd9eb67345849f24f55',
    messagingSenderId: '368339982928',
    projectId: 'eco-cycle-f777d',
    authDomain: 'eco-cycle-f777d.firebaseapp.com',
    storageBucket: 'eco-cycle-f777d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Wyuq8IN9Zn_e9pOrU_Wd8iAbprcoXFM',
    appId: '1:368339982928:android:614b3d38c3da922ef24f55',
    messagingSenderId: '368339982928',
    projectId: 'eco-cycle-f777d',
    storageBucket: 'eco-cycle-f777d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvXoKgXFH6IkbkBxufv92uitB-rISVh5g',
    appId: '1:368339982928:ios:4d82a19a7af053eff24f55',
    messagingSenderId: '368339982928',
    projectId: 'eco-cycle-f777d',
    storageBucket: 'eco-cycle-f777d.firebasestorage.app',
    iosBundleId: 'com.example.ecoCycle',
  );

}